### ISSUE TITLE
Cant open multiple graphics windows in Player on Mac OS 10.15.(1,2,3)

### ISSUE THREAD

**Issue by jpsluka** [CompuCell3D/CompuCell3D#199]
Opening multiple graphics windows on Mac OS 10.15.3 crashes player.
```
Traceback (most recent call last):
  File "/Users/jamessluka/Desktop/CC3D_4.1.1/lib/site-packages/cc3d/player5/Plugins/ViewManagerPlugins/SimpleTabView.py", line 431, in add_new_graphics_window
    suggested_win_pos = self.suggested_window_position()
  File "/Users/jamessluka/Desktop/CC3D_4.1.1/lib/site-packages/cc3d/player5/Plugins/ViewManagerPlugins/MainArea.py", line 133, in suggested_window_position
    self.last_suggested_window_position = QPoint(randint(rec.width() / 5, rec.width() / 2),
  File "/Users/jamessluka/Desktop/CC3D_4.1.1/python37/lib/python3.7/random.py", line 222, in randint
    return self.randrange(a, b+1)
  File "/Users/jamessluka/Desktop/CC3D_4.1.1/python37/lib/python3.7/random.py", line 186, in randrange
    raise ValueError("non-integer arg 1 for randrange()")
ValueError: non-integer arg 1 for randrange()
CLOSING LOCAL SOCKET
```
Mac OS 10.15.3, CC3D 4.1.1

**Comment by jpsluka** [comment]
Mac OS 10.15.x

**Comment by jpsluka** [comment]
The bacterium_macrophage_new_style demo crashes on a Mac running 10.15.x but runs OK on a Mac 10.11.6.
