### ISSUE TITLE
Strange error with player settings in headless mode (occurs only sometimes).

### ISSUE THREAD

**Issue by gabroo** [CompuCell3D/CompuCell3D#329]
Running within a Singularity container based on Ubuntu 20.04, VTK 9 with OSMesa, CC3D 4.2.2.

This happens only sometimes. I started a batch job of 3 iterations of running 128x simulations at 10k mcs each. This only happened on the third iteration, ie, after 256 simulations had finished successfully.

This is quite strange. I'm not sure why this code is even running since I thought the `screenshot_data.json` file was where it gets all these settings. Any guidance would be much appreciated.

```python
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/cc3d/CompuCellSetup/sim_runner.py", line 77, in run_cc3d_project
    exec(code, globals(), locals())
  File "/scratch2/sajeevsa/evomorph/2020-08-16/gen_001/sim_096/Simulation/sim.py", line 16, in <module>
    CompuCellSetup.run()
  File "/usr/local/lib/python3.7/site-packages/cc3d/CompuCellSetup/simulation_setup.py", line 117, in run
    main_loop_fcn(simulator, simthread=simthread, steppable_registry=steppable_registry)
  File "/usr/local/lib/python3.7/site-packages/cc3d/CompuCellSetup/simulation_setup.py", line 447, in main_loop
    init_screenshot_manager()
  File "/usr/local/lib/python3.7/site-packages/cc3d/CompuCellSetup/simulation_setup.py", line 343, in init_screenshot_manager
    gd = GenericDrawer.GenericDrawer()
  File "/usr/local/lib/python3.7/site-packages/cc3d/core/GraphicsOffScreen/GenericDrawer.py", line 61, in __init__
    self.draw_view_3D = MVCDrawView3D(self.draw_model_3D)
  File "/usr/local/lib/python3.7/site-packages/cc3d/core/GraphicsOffScreen/MVCDrawView3D.py", line 15, in __init__
    self.initArea()
  File "/usr/local/lib/python3.7/site-packages/cc3d/core/GraphicsOffScreen/MVCDrawView3D.py", line 39, in initArea
    self.set3DInvisibleTypes()
  File "/usr/local/lib/python3.7/site-packages/cc3d/core/GraphicsOffScreen/MVCDrawView3D.py", line 232, in set3DInvisibleTypes
    self.colorMap = Configuration.getSetting("TypeColorMap")
  File "/usr/local/lib/python3.7/site-packages/cc3d/player5/Configuration/__init__.py", line 312, in getSetting
    val = setting_storage.getSetting(_key)
  File "/usr/local/lib/python3.7/site-packages/cc3d/player5/Configuration/settingdict.py", line 435, in getSetting
    return self.setting(key)
  File "/usr/local/lib/python3.7/site-packages/cc3d/player5/Configuration/settingdict.py", line 421, in setting
    "SELECT type, value FROM settings WHERE name = (?)", (key,))
sqlite3.DatabaseError: database disk image is malformed
```

**Comment by CompuCell3D** [comment]
I think this might be a race condition where multiple players ry to write settings to the same simulation. One simple way of dealing with it is to create separate replicas of the folder with .cc3d project and run those like that. Probably the easies solution. try and see if this works

**Comment by gabroo** [comment]
> I think this might be a race condition where multiple players ry to write settings to the same simulation. 

Sure, but why is the color map or any other property being read from the player5 database? Is there a database being created from the `screenshot_data.json` file? I don't have any settings db files in any of the directories.

> One simple way of dealing with it is to create separate replicas of the folder with .cc3d project and run those like that. Probably the easies solution. try and see if this works

This is already being done, the code is [here](https://github.com/gabroo/evomorph/blob/hpc/src/tools/simulation.py). I'm using the same style as your `CC3DCaller` demo.

**Comment by gabroo** [comment]
@CompuCell3D @maciekswat

**Comment by tjsego** [comment]
@CompuCell3D is right. This is a race condition associated with rendering in parallel. We have some prototypes to do parallel rendering via the Python API after simulations have been run, specifically to address this issue. For now, @gabroo try disabling any rendering when running the simulations and see if that helps.

**Comment by gabroo** [comment]
Hi, I've been getting around this issue by not using more workers than simulations.

Is it possible to get the VTK lattice output along with the screenshots?

**Comment by jpsluka** [comment]
Yep,you can save the VTK lattice, which will include the cell field and all the diffusable fields. In player go to <Tools><Configuration> and click the checkbox for "Save visualization snapshots every Nth MCS". This will create a folder called "LatticeData" in your output folder. There will be a VTK file every Nth mcs.

You can also reload the VTK files into CC3D using <File><Open Lattice Description Summary File...> and then browsing to your output folder, then the LatticeData folder, then select the StepLDF.dml file. Now clicking on the go button in player will step through the VTK shots.

![image](https://user-images.githubusercontent.com/22944062/96493446-05727d80-1213-11eb-9a50-c5edca9ea7bf.png)

**Comment by gabroo** [comment]
@jpsluka sorry I should have specified I'm on a headless environment without the GUI; I'm using the `CC3DCaller` API and invoking the simulation directly from Python script

**Comment by gabroo** [comment]
The LatticeData folder is being created, along with the StepLDF.dml config file, but none of the lattice files are being output

**Comment by tjsego** [comment]
> The LatticeData folder is being created, along with the StepLDF.dml config file, but none of the lattice files are being output

To generate lattice data using ``CC3DCaller``, try setting the keyword argument ``output_frequency`` with a nonzero value.
