### ISSUE TITLE
runScript fails to run simulations that use Python-defined player fields

### ISSUE THREAD

**Issue by CompuCell3D** [CompuCell3D/CompuCell3D#425]
When running simulation that uses custom visualization fields e.g. `Demos/CompuCellPythonTutorial/ExtraFields/ExtraFields.cc3d` using runScript.bat we get this error where  pg.persistent_holder['field_storage'] entry is missing:

`Traceback (most recent call last):
  File "D:\CC3D_PY3_GIT\cc3d\CompuCellSetup\sim_runner.py", line 77, in run_cc3d_project
    exec(code, globals(), locals())
  File "d:\CC3D_PY3_GIT\CompuCell3D\core\Demos_local\Durotaxis_2\Simulation\Durotaxis.py", line 6, in <module>
    CompuCellSetup.run()
  File "D:\CC3D_PY3_GIT\cc3d\CompuCellSetup\simulation_setup.py", line 112, in run
    field_registry.create_fields()
  File "D:\CC3D_PY3_GIT\cc3d\core\FieldRegistry.py", line 169, in create_fields
    field_creating_fcn(field_name)
  File "D:\CC3D_PY3_GIT\cc3d\core\FieldRegistry.py", line 111, in create_scalar_field_cell_level
    field_ref = self.get_field_storage().createScalarFieldCellLevelPy(field_name)
  File "D:\CC3D_PY3_GIT\cc3d\core\FieldRegistry.py", line 250, in get_field_storage
    return pg.persistent_holder['field_storage']
KeyError: 'field_storage'`

**Comment by jpsluka** [comment]
Durotaxis is one of the visual demos, not part of the CC3D distribution. Was the person actually running that demo?

**Comment by CompuCell3D** [comment]
We ran it internally only,  just too test

**Comment by tjsego** [comment]
This is an issue of using CC3D core functionality before the core is available. If anything, this should be intended behavior and Player functionality should be revised to impose the same.
