### ISSUE TITLE
PyQt5.QtGui' has no attribute 'QFrame'

### ISSUE THREAD

**Issue by tahreem-zaheer** [CompuCell3D/CompuCell3D#462]
I am trying to install CompuCell3D on my OS (Ubuntu 20.04.2 LTS) 64-bit through miniconda. But I am facing errors. The most recent error is stated herewith. 

./compucell3d.sh 
./compucell3d.sh: 10: Bad substitution
/home/410_auto/lib/site-packages/cc3d/cpp/CompuCell3DSteppables/
/home/410_auto/lib/site-packages/cc3d/cpp/CompuCell3DPlugins/
Traceback (most recent call last):
  File "/home/410_auto/lib/site-packages/cc3d/player5/compucell3d.pyw", line 15, in <module>
    from cc3d.player5.UI.UserInterface import UserInterface
  File "/home/410_auto/lib/site-packages/cc3d/player5/UI/UserInterface.py", line 16, in <module>
    from cc3d.player5.Plugins.ViewManagerPlugins.SimpleTabView import SimpleTabView
  File "/home/410_auto/lib/site-packages/cc3d/player5/Plugins/ViewManagerPlugins/SimpleTabView.py", line 34, in <module>
    from .PlotManagerSetup import create_plot_manager
  File "/home/410_auto/lib/site-packages/cc3d/player5/Plugins/ViewManagerPlugins/PlotManagerSetup.py", line 7, in <module>
    from .PlotManager import PlotManager
  File "/home/410_auto/lib/site-packages/cc3d/player5/Plugins/ViewManagerPlugins/PlotManager.py", line 4, in <module>
    from cc3d.player5.Graphics.PlotFrameWidget import PlotFrameWidget
  File "/home/410_auto/lib/site-packages/cc3d/player5/Graphics/PlotFrameWidget.py", line 15, in <module>
    class PlotFrameWidget(QtGui.QFrame):
AttributeError: module 'PyQt5.QtGui' has no attribute 'QFrame'

**Comment by tjsego** [comment]
@tahreem-zaheer try building from [fix/pyqt_imports](https://github.com/CompuCell3D/CompuCell3D/tree/fix/pyqt_imports) and see if the fixes resolve this issue on your machine.

**Comment by tahreem-zaheer** [comment]
IT WORKED! 

Thank you so much!

Tahreem Zaheer
Researcher ELTE-TTK Budapest, HungaryLocal Phone: +36205732391WhatsApp Phone: +92-336-5458035https://www.researchgate.net/profile/Tahreem_Zaheer3



 

    On Monday, July 19, 2021, 12:34:05 PM GMT+2, tjsego ***@***.***> wrote:  
 
 


@tahreem-zaheer try building from fix/pyqt_imports and see if the fixes resolve this issue on your machine.
