### ISSUE TITLE
self.reaction_diffusion_solver_fvm.getCellDiffusivityCoefficient function not working

### ISSUE THREAD

**Issue by VaninJoel** [CompuCell3D/CompuCell3D#704]
I am having trouble when trying to change the DiffusionCoefficient of a single cell using the suggested code on Twedit. Running on Windows on version 4.4.1, Here is the error message 
`Error: AttributeError: 'NoneType' object has no attribute 'getCellDiffusivityCoefficient'
Traceback (most recent call last):
  File "C:\CompuCell3D\Miniconda3\lib\site-packages\cc3d\CompuCellSetup\sim_runner.py", line 79, in run_cc3d_project
    exec(code, globals(), locals())
  File "C:\Users\joelv\Documents\GitHub\vCornea\Epithelium\HPC\Project\vCornea_v_PaperHPC_version_9\Simulation\vCornea_TENTATIVE0.py", line 62, in <module>
    CompuCellSetup.run()
  File "C:\CompuCell3D\Miniconda3\lib\site-packages\cc3d\CompuCellSetup\simulation_setup.py", line 160, in run
    main_loop_fcn(simulator, simthread=simthread, steppable_registry=steppable_registry)
  File "C:\CompuCell3D\Miniconda3\lib\site-packages\cc3d\player5\Simulation\main_loops.py", line 74, in main_loop_player
    steppable_registry.step(cur_step)
  File "C:\CompuCell3D\Miniconda3\lib\site-packages\cc3d\core\SteppableRegistry.py", line 152, in step
    steppable.step(_mcs)
  File "C:\Users\joelv\Documents\GitHub\vCornea\Epithelium\HPC\Project\vCornea_v_PaperHPC_version_9\Simulation\vCornea_TENTATIVE0Steppables.py", line 402, in step
    cell_diff = self.reaction_diffusion_solver_fvm.getCellDiffusivityCoefficient(cell, "EGF")
AttributeError: 'NoneType' object has no attribute 'getCellDiffusivityCoefficient'`

From the File ReactionDiffusionSolverFVM.h we have the definition of `'double getCellDiffusivityCoefficient(const CellG * _cell, unsigned int _fieldIndex);
		
		/**
		 * @brief collects diffusivity coefficients for _cell and returns the value at _fieldIndex
		 * If the size of diffusivity coefficient vector is less than _fieldIndex, cell diffusivity
		 * coefficients are initialised on the fly 
		 * _fieldIndex is obtained from _fieldName
		 * 
		 * @param _cell 
		 * @param _fieldName 
		 * @return double 
		 */
		virtual double getCellDiffusivityCoefficient(const CellG * _cell, std::string _fieldName) { return getCellDiffusivityCoefficient(_cell, getFieldIndexByName(_fieldName)); }
		
		/**
		 * @brief gets a vector of diffusivity coefficients for _cell and adds _diffusivityCoefficient 
		 * at _fieldIndex in the diffusivity coefficients vector
		 * 
		 * @param _cell 
		 * @param _fieldIndex 
		 * @param _diffusivityCoefficient 
		 */`

And from the PySteppables.py we have: 
`def __init__(self, *args, **kwds):
...
      #: (dict of [str: str]) map of steppables names to attribute reference names
        self.steppable_init_dict = {
            "ReactionDiffusionSolverFVM": ['reaction_diffusion_solver_fvm']
        }`

**Comment by VaninJoel** [comment]
More information this the part of the code that calls it and the tests that I did with its results: 
`elif cell.type == self.SUPER: 
                cell.dict['EGF_Uptake'] = abs(self.EGF_Field.uptakeInsideCellTotalCount(cell, 100000.0, self.EGF_FieldUptakeSuper).tot_amount)          
               
                # TODO check if this is working correctly 
                print(dir(self.reaction_diffusion_solver_fvm))
                print(type(self.reaction_diffusion_solver_fvm))  # NONE         
                cell_diff = self.reaction_diffusion_solver_fvm.getCellDiffusivityCoefficient(cell, "EGF")
                print(cell_diff, "cell diff")`
['__bool__', '__class__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__']
<class 'NoneType'>
error message...

**Comment by tjsego** [comment]
As a quick sanity check, can you successfully execute [this demo](https://github.com/CompuCell3D/CompuCell3D/tree/master/CompuCell3D/core/Demos/SteppableDemos/ReactionDiffusionSolverFVM/HeterogeneousBCDemo)?
